name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        run: |
          scp -r . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/deployment

      - name: Install PM2 and Start Application
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          cd /home/${{ secrets.EC2_USERNAME }}/deployment

          if [ -f package.json ]; then
            npm install --production
          fi
          
            pm2 restart all
          
          fi
          EOF
