name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Archive the build artifacts
      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz dist/ node_modules/
      
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Upload build artifacts to the EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build-artifacts.tar.gz"
          target: "/home/ubuntu/Nestjs_Hello_world_app/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            cd /home/ubuntu/Nestjs_Hello_world_app
            tar -xzf build-artifacts.tar.gz
            # If PM2 is not installed, install it globally
            if ! pm2 -v > /dev/null 2>&1; then
              npm install pm2@latest -g
            fi
            # Start the application using PM2
            pm2 delete all || true
            pm2 start dist/main.js --name nestjs-app
            pm2 save
            pm2 startup

      - name: Clean up
        run: rm key.pem build-artifacts.tar.gz
