name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Archive the build artifacts
      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz dist/ node_modules/

      - name: Upload build artifacts to the EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build-artifacts.tar.gz"
          target: "/home/ubuntu/Nestjs_Hello_world_app/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e

            # Navigate to the application directory
            cd /home/ubuntu/Nestjs_Hello_world_app

            # Pull the latest code from the repository
            git pull origin master

            # Verify the tar file exists
            if [ -f build-artifacts.tar.gz ]; then
              echo "Build artifacts found!"
            else
              echo "Build artifacts not found!"
              exit 1
            fi

            # Extract the build artifacts
            tar -xzf build-artifacts.tar.gz

            # Ensure PM2 is installed globally
            if ! which pm2 >/dev/null 2>&1; then
              echo "PM2 not found, installing..."
              npm install pm2@latest -g
            fi

            # Add npm global bin to PATH in case it's not available
            export PATH=$PATH:$(npm bin -g)

            # Ensure PM2 is available in PATH
            if ! which pm2 >/dev/null 2>&1; then
              echo "PM2 still not found in PATH!"
              exit 1
            fi

            # Stop previous PM2 processes if any
            if pm2 status | grep -q 'nestjs-app'; then
              echo "Stopping existing PM2 process..."
              pm2 stop nestjs-app
              pm2 delete nestjs-app
            fi

            # Start the application using PM2
            echo "Starting application with PM2..."
            pm2 start dist/main.js --name nestjs-app

            # Save PM2 process list and enable startup script
            pm2 save

            # Ensure the user and home path are set correctly for the startup command
            sudo pm2 startup systemd -u $USER

      - name: Clean up
        run: rm build-artifacts.tar.gz
