name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive project files
        run: |
          zip -r archive.zip ./*

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: nestjs-archive
          path: archive.zip

      - name: Debug - Print Environment Variables
        run: env

      - name: Debug - Print Current Directory
        run: ls -al

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Install unzip if not already installed
            if ! command -v unzip &> /dev/null; then
              sudo apt-get update -y && sudo apt-get install unzip -y
            fi

            mkdir -p /home/${{ secrets.EC2_USERNAME }}/deployment || exit 1
            cd /home/${{ secrets.EC2_USERNAME }}/deployment || exit 1
            unzip -o /home/${{ secrets.EC2_USERNAME }}/deployment/archive.zip || exit 1
            npm install --production || exit 1
            pm2 restart all || exit 1  # or any other command to restart your server

      - name: Debug - Check EC2 Deployment Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/deployment
            ls -al
