name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Archive the build artifacts
      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz dist/ node_modules/
      
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Upload build artifacts to the EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "build-artifacts.tar.gz"
          target: "/home/ubuntu/Nestjs_Hello_world_app/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            set -e

            # Navigate to the application directory
            cd /home/ubuntu/Nestjs_Hello_world_app

            # Verify the tar file exists
            if [ ! -f build-artifacts.tar.gz ]; then
              echo "Build artifacts not found!"
              exit 1
            fi

            # Extract the build artifacts
            tar -xzf build-artifacts.tar.gz

            # Check if PM2 is installed, if not install it
            if ! command -v pm2 >/dev/null 2>&1; then
              echo "PM2 not found, installing..."
              npm install pm2@latest -g
            fi

            # Stop previous PM2 processes if any
            if pm2 status | grep -q 'nestjs-app'; then
              echo "Stopping existing PM2 process..."
              pm2 stop nestjs-app
              pm2 delete nestjs-app
            fi

            # Start the application using PM2
            echo "Starting application with PM2..."
            pm2 start dist/main.js --name nestjs-app

            # Save PM2 process list and enable startup script
            pm2 save
            sudo env PATH=\$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER

      - name: Clean up
        run: rm key.pem build-artifacts.tar.gz
